SOCIAL_PLATFORMS = [
    ('amazon', 'Amazon'),
    ('angellist', 'AngelList'),
    ('digitalocean', 'DigitalOcean'),
    ('discord', 'Discord'),
    ('dropbox', 'Dropbox'),
    ('facebook', 'Facebook'),
    ('figma', 'Figma'),
    ('frontier', 'Frontier'),
    ('fxa', 'Firefox Accounts'),
    ('gitea', 'Gitea'),
    ('github', 'GitHub'),
    ('gitlab', 'GitLab'),
    ('google', 'Google'),
    ('gumroad', 'Gumroad'),
    ('instagram', 'Instagram'),
    ('linkedin', 'LinkedIn'),
    ('meetup', 'Meetup'),
    ('microsoft', 'Microsoft'),
    ('notion', 'Notion'),
    ('openid_connect', 'OpenID Connect'),
    ('pinterest', 'Pinterest'),
    ('reddit', 'Reddit'),
    ('shopify', 'Shopify'),
    ('slack', 'Slack'),
    ('snapchat', 'Snapchat'),
    ('soundcloud', 'SoundCloud'),
    ('spotify', 'Spotify'),
    ('telegram', 'Telegram'),
    ('twitch', 'Twitch'),
    ('twitter', 'Twitter'),
    ('vimeo', 'Vimeo'),
    ('vk', 'VK'),
    ('yahoo', 'Yahoo'),
    ('zoom', 'Zoom'),
]

OAUTH_URLS = {
    'facebook': 'https://www.facebook.com/v12.0/dialog/oauth',
    'twitter': 'https://api.twitter.com/oauth/authenticate',
    'instagram': 'https://api.instagram.com/oauth/authorize',
    'linkedin': 'https://www.linkedin.com/oauth/v2/authorization',
    'pinterest': 'https://www.pinterest.com/oauth/',
    'reddit': 'https://www.reddit.com/api/v1/authorize',
    'google': 'https://accounts.google.com/o/oauth2/auth',
    'youtube': 'https://accounts.google.com/o/oauth2/auth',
}
